# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

alias k='kubectl'
alias ksys='kubectl --namespace=kube-system'
alias ka='kubectl apply --recursive -f'
alias ksysa='kubectl --namespace=kube-system apply --recursive -f'
alias kex='kubectl exec -i -t'
alias ksysex='kubectl --namespace=kube-system exec -i -t'
alias ked='kubectl edit'
alias ksysed='kubectl --namespace=kube-system edit'
alias klo='kubectl logs -f'
alias ksyslo='kubectl --namespace=kube-system logs -f'
alias klop='kubectl logs -f -p'
alias ksyslop='kubectl --namespace=kube-system logs -f -p'
alias kp='kubectl proxy'
alias kg='kubectl get'
alias ksysg='kubectl --namespace=kube-system get'
alias kd='kubectl describe'
alias ksysd='kubectl --namespace=kube-system describe'
alias krm='kubectl delete'
alias ksysrm='kubectl --namespace=kube-system delete'
alias krun='kubectl run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t'
alias ksysrun='kubectl --namespace=kube-system run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t'
alias kt='kubectl top'
alias ksyst='kubectl --namespace=kube-system top'
alias kpf='kubectl port-forward'
alias ksyspf='kubectl --namespace=kube-system port-forward'
alias kedpo='kubectl edit pods'
alias ksysedpo='kubectl --namespace=kube-system edit pods'
alias kgpo='kubectl get pods'
alias ksysgpo='kubectl --namespace=kube-system get pods'
alias kdpo='kubectl describe pods'
alias ksysdpo='kubectl --namespace=kube-system describe pods'
alias krmpo='kubectl delete pods'
alias ksysrmpo='kubectl --namespace=kube-system delete pods'
alias ktpo='kubectl top pods'
alias ksystpo='kubectl --namespace=kube-system top pods'
alias kgev='kubectl get events'
alias ksysgev='kubectl --namespace=kube-system get events'
alias kdev='kubectl describe events'
alias ksysdev='kubectl --namespace=kube-system describe events'
alias keddep='kubectl edit deployment'
alias ksyseddep='kubectl --namespace=kube-system edit deployment'
alias kgdep='kubectl get deployment'
alias ksysgdep='kubectl --namespace=kube-system get deployment'
alias kddep='kubectl describe deployment'
alias ksysddep='kubectl --namespace=kube-system describe deployment'
alias krmdep='kubectl delete deployment'
alias ksysrmdep='kubectl --namespace=kube-system delete deployment'
alias kedsvc='kubectl edit service'
alias ksysedsvc='kubectl --namespace=kube-system edit service'
alias kgsvc='kubectl get service'
alias ksysgsvc='kubectl --namespace=kube-system get service'
alias kdsvc='kubectl describe service'
alias ksysdsvc='kubectl --namespace=kube-system describe service'
alias krmsvc='kubectl delete service'
alias ksysrmsvc='kubectl --namespace=kube-system delete service'
alias keding='kubectl edit ingress'
alias ksyseding='kubectl --namespace=kube-system edit ingress'
alias kging='kubectl get ingress'
alias ksysging='kubectl --namespace=kube-system get ingress'
alias kding='kubectl describe ingress'
alias ksysding='kubectl --namespace=kube-system describe ingress'
alias krming='kubectl delete ingress'
alias ksysrming='kubectl --namespace=kube-system delete ingress'
alias kedcm='kubectl edit configmap'
alias ksysedcm='kubectl --namespace=kube-system edit configmap'
alias kgcm='kubectl get configmap'
alias ksysgcm='kubectl --namespace=kube-system get configmap'
alias kdcm='kubectl describe configmap'
alias ksysdcm='kubectl --namespace=kube-system describe configmap'
alias krmcm='kubectl delete configmap'
alias ksysrmcm='kubectl --namespace=kube-system delete configmap'
alias kedsec='kubectl edit secret'
alias ksysedsec='kubectl --namespace=kube-system edit secret'
alias kgsec='kubectl get secret'
alias ksysgsec='kubectl --namespace=kube-system get secret'
alias kdsec='kubectl describe secret'
alias ksysdsec='kubectl --namespace=kube-system describe secret'
alias krmsec='kubectl delete secret'
alias ksysrmsec='kubectl --namespace=kube-system delete secret'
alias kedno='kubectl edit nodes'
alias kgno='kubectl get nodes'
alias kdno='kubectl describe nodes'
alias ktno='kubectl top nodes'
alias kedns='kubectl edit namespaces'
alias kgns='kubectl get namespaces'
alias kdns='kubectl describe namespaces'
alias krmns='kubectl delete namespaces'
alias kedpvc='kubectl edit persistentvolumeclaim'
alias ksysedpvc='kubectl --namespace=kube-system edit persistentvolumeclaim'
alias kgpvc='kubectl get persistentvolumeclaim'
alias ksysgpvc='kubectl --namespace=kube-system get persistentvolumeclaim'
alias kdpvc='kubectl describe persistentvolumeclaim'
alias ksysdpvc='kubectl --namespace=kube-system describe persistentvolumeclaim'
alias krmpvc='kubectl delete persistentvolumeclaim'
alias ksysrmpvc='kubectl --namespace=kube-system delete persistentvolumeclaim'
alias kedpv='kubectl edit persistentvolume'
alias ksysedpv='kubectl --namespace=kube-system edit persistentvolume'
alias kgpv='kubectl get persistentvolume'
alias ksysgpv='kubectl --namespace=kube-system get persistentvolume'
alias kdpv='kubectl describe persistentvolume'
alias ksysdpv='kubectl --namespace=kube-system describe persistentvolume'
alias krmpv='kubectl delete persistentvolume'
alias ksysrmpv='kubectl --namespace=kube-system delete persistentvolume'
alias kgoyaml='kubectl get -o=yaml'
alias ksysgoyaml='kubectl --namespace=kube-system get -o=yaml'
alias kgpooyaml='kubectl get pods -o=yaml'
alias ksysgpooyaml='kubectl --namespace=kube-system get pods -o=yaml'
alias kgevoyaml='kubectl get events -o=yaml'
alias ksysgevoyaml='kubectl --namespace=kube-system get events -o=yaml'
alias kgdepoyaml='kubectl get deployment -o=yaml'
alias ksysgdepoyaml='kubectl --namespace=kube-system get deployment -o=yaml'
alias kgsvcoyaml='kubectl get service -o=yaml'
alias ksysgsvcoyaml='kubectl --namespace=kube-system get service -o=yaml'
alias kgingoyaml='kubectl get ingress -o=yaml'
alias ksysgingoyaml='kubectl --namespace=kube-system get ingress -o=yaml'
alias kgcmoyaml='kubectl get configmap -o=yaml'
alias ksysgcmoyaml='kubectl --namespace=kube-system get configmap -o=yaml'
alias kgsecoyaml='kubectl get secret -o=yaml'
alias ksysgsecoyaml='kubectl --namespace=kube-system get secret -o=yaml'
alias kgnooyaml='kubectl get nodes -o=yaml'
alias kgnsoyaml='kubectl get namespaces -o=yaml'
alias kgpvcoyaml='kubectl get persistentvolumeclaim -o=yaml'
alias ksysgpvcoyaml='kubectl --namespace=kube-system get persistentvolumeclaim -o=yaml'
alias kgpvoyaml='kubectl get persistentvolume -o=yaml'
alias ksysgpvoyaml='kubectl --namespace=kube-system get persistentvolume -o=yaml'
alias kgowide='kubectl get -o=wide'
alias ksysgowide='kubectl --namespace=kube-system get -o=wide'
alias kgpoowide='kubectl get pods -o=wide'
alias ksysgpoowide='kubectl --namespace=kube-system get pods -o=wide'
alias kgevowide='kubectl get events -o=wide'
alias ksysgevowide='kubectl --namespace=kube-system get events -o=wide'
alias kgdepowide='kubectl get deployment -o=wide'
alias ksysgdepowide='kubectl --namespace=kube-system get deployment -o=wide'
alias kgsvcowide='kubectl get service -o=wide'
alias ksysgsvcowide='kubectl --namespace=kube-system get service -o=wide'
alias kgingowide='kubectl get ingress -o=wide'
alias ksysgingowide='kubectl --namespace=kube-system get ingress -o=wide'
alias kgcmowide='kubectl get configmap -o=wide'
alias ksysgcmowide='kubectl --namespace=kube-system get configmap -o=wide'
alias kgsecowide='kubectl get secret -o=wide'
alias ksysgsecowide='kubectl --namespace=kube-system get secret -o=wide'
alias kgnoowide='kubectl get nodes -o=wide'
alias kgnsowide='kubectl get namespaces -o=wide'
alias kgpvcowide='kubectl get persistentvolumeclaim -o=wide'
alias ksysgpvcowide='kubectl --namespace=kube-system get persistentvolumeclaim -o=wide'
alias kgpvowide='kubectl get persistentvolume -o=wide'
alias ksysgpvowide='kubectl --namespace=kube-system get persistentvolume -o=wide'
alias kgall='kubectl get --all-namespaces'
alias kdall='kubectl describe --all-namespaces'
alias ktall='kubectl top --all-namespaces'
alias kgpoall='kubectl get pods --all-namespaces'
alias kdpoall='kubectl describe pods --all-namespaces'
alias ktpoall='kubectl top pods --all-namespaces'
alias kgevall='kubectl get events --all-namespaces'
alias kdevall='kubectl describe events --all-namespaces'
alias kgdepall='kubectl get deployment --all-namespaces'
alias kddepall='kubectl describe deployment --all-namespaces'
alias kgsvcall='kubectl get service --all-namespaces'
alias kdsvcall='kubectl describe service --all-namespaces'
alias kgingall='kubectl get ingress --all-namespaces'
alias kdingall='kubectl describe ingress --all-namespaces'
alias kgcmall='kubectl get configmap --all-namespaces'
alias kdcmall='kubectl describe configmap --all-namespaces'
alias kgsecall='kubectl get secret --all-namespaces'
alias kdsecall='kubectl describe secret --all-namespaces'
alias kgnsall='kubectl get namespaces --all-namespaces'
alias kdnsall='kubectl describe namespaces --all-namespaces'
alias kgpvcall='kubectl get persistentvolumeclaim --all-namespaces'
alias kdpvcall='kubectl describe persistentvolumeclaim --all-namespaces'
alias kgpvall='kubectl get persistentvolume --all-namespaces'
alias kdpvall='kubectl describe persistentvolume --all-namespaces'
alias kgsl='kubectl get --show-labels'
alias ksysgsl='kubectl --namespace=kube-system get --show-labels'
alias kgposl='kubectl get pods --show-labels'
alias ksysgposl='kubectl --namespace=kube-system get pods --show-labels'
alias kgdepsl='kubectl get deployment --show-labels'
alias ksysgdepsl='kubectl --namespace=kube-system get deployment --show-labels'
alias kgsecsl='kubectl get secret --show-labels'
alias ksysgsecsl='kubectl --namespace=kube-system get secret --show-labels'
alias kgnosl='kubectl get nodes --show-labels'
alias kgpvcsl='kubectl get persistentvolumeclaim --show-labels'
alias ksysgpvcsl='kubectl --namespace=kube-system get persistentvolumeclaim --show-labels'
alias kgpvsl='kubectl get persistentvolume --show-labels'
alias ksysgpvsl='kubectl --namespace=kube-system get persistentvolume --show-labels'
alias krmall='kubectl delete --all'
alias ksysrmall='kubectl --namespace=kube-system delete --all'
alias krmpoall='kubectl delete pods --all'
alias ksysrmpoall='kubectl --namespace=kube-system delete pods --all'
alias krmdepall='kubectl delete deployment --all'
alias ksysrmdepall='kubectl --namespace=kube-system delete deployment --all'
alias krmsvcall='kubectl delete service --all'
alias ksysrmsvcall='kubectl --namespace=kube-system delete service --all'
alias krmingall='kubectl delete ingress --all'
alias ksysrmingall='kubectl --namespace=kube-system delete ingress --all'
alias krmcmall='kubectl delete configmap --all'
alias ksysrmcmall='kubectl --namespace=kube-system delete configmap --all'
alias krmsecall='kubectl delete secret --all'
alias ksysrmsecall='kubectl --namespace=kube-system delete secret --all'
alias krmnsall='kubectl delete namespaces --all'
alias krmpvcall='kubectl delete persistentvolumeclaim --all'
alias ksysrmpvcall='kubectl --namespace=kube-system delete persistentvolumeclaim --all'
alias krmpvall='kubectl delete persistentvolume --all'
alias ksysrmpvall='kubectl --namespace=kube-system delete persistentvolume --all'
alias kgw='kubectl get --watch'
alias ksysgw='kubectl --namespace=kube-system get --watch'
alias kgpow='kubectl get pods --watch'
alias ksysgpow='kubectl --namespace=kube-system get pods --watch'
alias kgevw='kubectl get events --watch'
alias ksysgevw='kubectl --namespace=kube-system get events --watch'
alias kgdepw='kubectl get deployment --watch'
alias ksysgdepw='kubectl --namespace=kube-system get deployment --watch'
alias kgsvcw='kubectl get service --watch'
alias ksysgsvcw='kubectl --namespace=kube-system get service --watch'
alias kgingw='kubectl get ingress --watch'
alias ksysgingw='kubectl --namespace=kube-system get ingress --watch'
alias kgcmw='kubectl get configmap --watch'
alias ksysgcmw='kubectl --namespace=kube-system get configmap --watch'
alias kgsecw='kubectl get secret --watch'
alias ksysgsecw='kubectl --namespace=kube-system get secret --watch'
alias kgnow='kubectl get nodes --watch'
alias kgnsw='kubectl get namespaces --watch'
alias kgpvcw='kubectl get persistentvolumeclaim --watch'
alias ksysgpvcw='kubectl --namespace=kube-system get persistentvolumeclaim --watch'
alias kgpvw='kubectl get persistentvolume --watch'
alias ksysgpvw='kubectl --namespace=kube-system get persistentvolume --watch'
alias kgoyamlall='kubectl get -o=yaml --all-namespaces'
alias kgpooyamlall='kubectl get pods -o=yaml --all-namespaces'
alias kgevoyamlall='kubectl get events -o=yaml --all-namespaces'
alias kgdepoyamlall='kubectl get deployment -o=yaml --all-namespaces'
alias kgsvcoyamlall='kubectl get service -o=yaml --all-namespaces'
alias kgingoyamlall='kubectl get ingress -o=yaml --all-namespaces'
alias kgcmoyamlall='kubectl get configmap -o=yaml --all-namespaces'
alias kgsecoyamlall='kubectl get secret -o=yaml --all-namespaces'
alias kgnsoyamlall='kubectl get namespaces -o=yaml --all-namespaces'
alias kgpvcoyamlall='kubectl get persistentvolumeclaim -o=yaml --all-namespaces'
alias kgpvoyamlall='kubectl get persistentvolume -o=yaml --all-namespaces'
alias kgalloyaml='kubectl get --all-namespaces -o=yaml'
alias kgpoalloyaml='kubectl get pods --all-namespaces -o=yaml'
alias kgevalloyaml='kubectl get events --all-namespaces -o=yaml'
alias kgdepalloyaml='kubectl get deployment --all-namespaces -o=yaml'
alias kgsvcalloyaml='kubectl get service --all-namespaces -o=yaml'
alias kgingalloyaml='kubectl get ingress --all-namespaces -o=yaml'
alias kgcmalloyaml='kubectl get configmap --all-namespaces -o=yaml'
alias kgsecalloyaml='kubectl get secret --all-namespaces -o=yaml'
alias kgnsalloyaml='kubectl get namespaces --all-namespaces -o=yaml'
alias kgpvcalloyaml='kubectl get persistentvolumeclaim --all-namespaces -o=yaml'
alias kgpvalloyaml='kubectl get persistentvolume --all-namespaces -o=yaml'
alias kgwoyaml='kubectl get --watch -o=yaml'
alias ksysgwoyaml='kubectl --namespace=kube-system get --watch -o=yaml'
alias kgpowoyaml='kubectl get pods --watch -o=yaml'
alias ksysgpowoyaml='kubectl --namespace=kube-system get pods --watch -o=yaml'
alias kgevwoyaml='kubectl get events --watch -o=yaml'
alias ksysgevwoyaml='kubectl --namespace=kube-system get events --watch -o=yaml'
alias kgdepwoyaml='kubectl get deployment --watch -o=yaml'
alias ksysgdepwoyaml='kubectl --namespace=kube-system get deployment --watch -o=yaml'
alias kgsvcwoyaml='kubectl get service --watch -o=yaml'
alias ksysgsvcwoyaml='kubectl --namespace=kube-system get service --watch -o=yaml'
alias kgingwoyaml='kubectl get ingress --watch -o=yaml'
alias ksysgingwoyaml='kubectl --namespace=kube-system get ingress --watch -o=yaml'
alias kgcmwoyaml='kubectl get configmap --watch -o=yaml'
alias ksysgcmwoyaml='kubectl --namespace=kube-system get configmap --watch -o=yaml'
alias kgsecwoyaml='kubectl get secret --watch -o=yaml'
alias ksysgsecwoyaml='kubectl --namespace=kube-system get secret --watch -o=yaml'
alias kgnowoyaml='kubectl get nodes --watch -o=yaml'
alias kgnswoyaml='kubectl get namespaces --watch -o=yaml'
alias kgpvcwoyaml='kubectl get persistentvolumeclaim --watch -o=yaml'
alias ksysgpvcwoyaml='kubectl --namespace=kube-system get persistentvolumeclaim --watch -o=yaml'
alias kgpvwoyaml='kubectl get persistentvolume --watch -o=yaml'
alias ksysgpvwoyaml='kubectl --namespace=kube-system get persistentvolume --watch -o=yaml'
alias kgowideall='kubectl get -o=wide --all-namespaces'
alias kgpoowideall='kubectl get pods -o=wide --all-namespaces'
alias kgevowideall='kubectl get events -o=wide --all-namespaces'
alias kgdepowideall='kubectl get deployment -o=wide --all-namespaces'
alias kgsvcowideall='kubectl get service -o=wide --all-namespaces'
alias kgingowideall='kubectl get ingress -o=wide --all-namespaces'
alias kgcmowideall='kubectl get configmap -o=wide --all-namespaces'
alias kgsecowideall='kubectl get secret -o=wide --all-namespaces'
alias kgnsowideall='kubectl get namespaces -o=wide --all-namespaces'
alias kgpvcowideall='kubectl get persistentvolumeclaim -o=wide --all-namespaces'
alias kgpvowideall='kubectl get persistentvolume -o=wide --all-namespaces'
alias kgallowide='kubectl get --all-namespaces -o=wide'
alias kgpoallowide='kubectl get pods --all-namespaces -o=wide'
alias kgevallowide='kubectl get events --all-namespaces -o=wide'
alias kgdepallowide='kubectl get deployment --all-namespaces -o=wide'
alias kgsvcallowide='kubectl get service --all-namespaces -o=wide'
alias kgingallowide='kubectl get ingress --all-namespaces -o=wide'
alias kgcmallowide='kubectl get configmap --all-namespaces -o=wide'
alias kgsecallowide='kubectl get secret --all-namespaces -o=wide'
alias kgnsallowide='kubectl get namespaces --all-namespaces -o=wide'
alias kgpvcallowide='kubectl get persistentvolumeclaim --all-namespaces -o=wide'
alias kgpvallowide='kubectl get persistentvolume --all-namespaces -o=wide'
alias kgowidesl='kubectl get -o=wide --show-labels'
alias ksysgowidesl='kubectl --namespace=kube-system get -o=wide --show-labels'
alias kgpoowidesl='kubectl get pods -o=wide --show-labels'
alias ksysgpoowidesl='kubectl --namespace=kube-system get pods -o=wide --show-labels'
alias kgdepowidesl='kubectl get deployment -o=wide --show-labels'
alias ksysgdepowidesl='kubectl --namespace=kube-system get deployment -o=wide --show-labels'
alias kgsecowidesl='kubectl get secret -o=wide --show-labels'
alias ksysgsecowidesl='kubectl --namespace=kube-system get secret -o=wide --show-labels'
alias kgnoowidesl='kubectl get nodes -o=wide --show-labels'
alias kgpvcowidesl='kubectl get persistentvolumeclaim -o=wide --show-labels'
alias ksysgpvcowidesl='kubectl --namespace=kube-system get persistentvolumeclaim -o=wide --show-labels'
alias kgpvowidesl='kubectl get persistentvolume -o=wide --show-labels'
alias ksysgpvowidesl='kubectl --namespace=kube-system get persistentvolume -o=wide --show-labels'
alias kgslowide='kubectl get --show-labels -o=wide'
alias ksysgslowide='kubectl --namespace=kube-system get --show-labels -o=wide'
alias kgposlowide='kubectl get pods --show-labels -o=wide'
alias ksysgposlowide='kubectl --namespace=kube-system get pods --show-labels -o=wide'
alias kgdepslowide='kubectl get deployment --show-labels -o=wide'
alias ksysgdepslowide='kubectl --namespace=kube-system get deployment --show-labels -o=wide'
alias kgsecslowide='kubectl get secret --show-labels -o=wide'
alias ksysgsecslowide='kubectl --namespace=kube-system get secret --show-labels -o=wide'
alias kgnoslowide='kubectl get nodes --show-labels -o=wide'
alias kgpvcslowide='kubectl get persistentvolumeclaim --show-labels -o=wide'
alias ksysgpvcslowide='kubectl --namespace=kube-system get persistentvolumeclaim --show-labels -o=wide'
alias kgpvslowide='kubectl get persistentvolume --show-labels -o=wide'
alias ksysgpvslowide='kubectl --namespace=kube-system get persistentvolume --show-labels -o=wide'
alias kgwowide='kubectl get --watch -o=wide'
alias ksysgwowide='kubectl --namespace=kube-system get --watch -o=wide'
alias kgpowowide='kubectl get pods --watch -o=wide'
alias ksysgpowowide='kubectl --namespace=kube-system get pods --watch -o=wide'
alias kgevwowide='kubectl get events --watch -o=wide'
alias ksysgevwowide='kubectl --namespace=kube-system get events --watch -o=wide'
alias kgdepwowide='kubectl get deployment --watch -o=wide'
alias ksysgdepwowide='kubectl --namespace=kube-system get deployment --watch -o=wide'
alias kgsvcwowide='kubectl get service --watch -o=wide'
alias ksysgsvcwowide='kubectl --namespace=kube-system get service --watch -o=wide'
alias kgingwowide='kubectl get ingress --watch -o=wide'
alias ksysgingwowide='kubectl --namespace=kube-system get ingress --watch -o=wide'
alias kgcmwowide='kubectl get configmap --watch -o=wide'
alias ksysgcmwowide='kubectl --namespace=kube-system get configmap --watch -o=wide'
alias kgsecwowide='kubectl get secret --watch -o=wide'
alias ksysgsecwowide='kubectl --namespace=kube-system get secret --watch -o=wide'
alias kgnowowide='kubectl get nodes --watch -o=wide'
alias kgnswowide='kubectl get namespaces --watch -o=wide'
alias kgpvcwowide='kubectl get persistentvolumeclaim --watch -o=wide'
alias ksysgpvcwowide='kubectl --namespace=kube-system get persistentvolumeclaim --watch -o=wide'
alias kgpvwowide='kubectl get persistentvolume --watch -o=wide'
alias ksysgpvwowide='kubectl --namespace=kube-system get persistentvolume --watch -o=wide'
alias kgallsl='kubectl get --all-namespaces --show-labels'
alias kgpoallsl='kubectl get pods --all-namespaces --show-labels'
alias kgdepallsl='kubectl get deployment --all-namespaces --show-labels'
alias kgsecallsl='kubectl get secret --all-namespaces --show-labels'
alias kgpvcallsl='kubectl get persistentvolumeclaim --all-namespaces --show-labels'
alias kgpvallsl='kubectl get persistentvolume --all-namespaces --show-labels'
alias kgslall='kubectl get --show-labels --all-namespaces'
alias kgposlall='kubectl get pods --show-labels --all-namespaces'
alias kgdepslall='kubectl get deployment --show-labels --all-namespaces'
alias kgsecslall='kubectl get secret --show-labels --all-namespaces'
alias kgpvcslall='kubectl get persistentvolumeclaim --show-labels --all-namespaces'
alias kgpvslall='kubectl get persistentvolume --show-labels --all-namespaces'
alias kgallw='kubectl get --all-namespaces --watch'
alias kgpoallw='kubectl get pods --all-namespaces --watch'
alias kgevallw='kubectl get events --all-namespaces --watch'
alias kgdepallw='kubectl get deployment --all-namespaces --watch'
alias kgsvcallw='kubectl get service --all-namespaces --watch'
alias kgingallw='kubectl get ingress --all-namespaces --watch'
alias kgcmallw='kubectl get configmap --all-namespaces --watch'
alias kgsecallw='kubectl get secret --all-namespaces --watch'
alias kgnsallw='kubectl get namespaces --all-namespaces --watch'
alias kgpvcallw='kubectl get persistentvolumeclaim --all-namespaces --watch'
alias kgpvallw='kubectl get persistentvolume --all-namespaces --watch'
alias kgwall='kubectl get --watch --all-namespaces'
alias kgpowall='kubectl get pods --watch --all-namespaces'
alias kgevwall='kubectl get events --watch --all-namespaces'
alias kgdepwall='kubectl get deployment --watch --all-namespaces'
alias kgsvcwall='kubectl get service --watch --all-namespaces'
alias kgingwall='kubectl get ingress --watch --all-namespaces'
alias kgcmwall='kubectl get configmap --watch --all-namespaces'
alias kgsecwall='kubectl get secret --watch --all-namespaces'
alias kgnswall='kubectl get namespaces --watch --all-namespaces'
alias kgpvcwall='kubectl get persistentvolumeclaim --watch --all-namespaces'
alias kgpvwall='kubectl get persistentvolume --watch --all-namespaces'
alias kgslw='kubectl get --show-labels --watch'
alias ksysgslw='kubectl --namespace=kube-system get --show-labels --watch'
alias kgposlw='kubectl get pods --show-labels --watch'
alias ksysgposlw='kubectl --namespace=kube-system get pods --show-labels --watch'
alias kgdepslw='kubectl get deployment --show-labels --watch'
alias ksysgdepslw='kubectl --namespace=kube-system get deployment --show-labels --watch'
alias kgsecslw='kubectl get secret --show-labels --watch'
alias ksysgsecslw='kubectl --namespace=kube-system get secret --show-labels --watch'
alias kgnoslw='kubectl get nodes --show-labels --watch'
alias kgpvcslw='kubectl get persistentvolumeclaim --show-labels --watch'
alias ksysgpvcslw='kubectl --namespace=kube-system get persistentvolumeclaim --show-labels --watch'
alias kgpvslw='kubectl get persistentvolume --show-labels --watch'
alias ksysgpvslw='kubectl --namespace=kube-system get persistentvolume --show-labels --watch'
alias kgwsl='kubectl get --watch --show-labels'
alias ksysgwsl='kubectl --namespace=kube-system get --watch --show-labels'
alias kgpowsl='kubectl get pods --watch --show-labels'
alias ksysgpowsl='kubectl --namespace=kube-system get pods --watch --show-labels'
alias kgdepwsl='kubectl get deployment --watch --show-labels'
alias ksysgdepwsl='kubectl --namespace=kube-system get deployment --watch --show-labels'
alias kgsecwsl='kubectl get secret --watch --show-labels'
alias ksysgsecwsl='kubectl --namespace=kube-system get secret --watch --show-labels'
alias kgnowsl='kubectl get nodes --watch --show-labels'
alias kgpvcwsl='kubectl get persistentvolumeclaim --watch --show-labels'
alias ksysgpvcwsl='kubectl --namespace=kube-system get persistentvolumeclaim --watch --show-labels'
alias kgpvwsl='kubectl get persistentvolume --watch --show-labels'
alias ksysgpvwsl='kubectl --namespace=kube-system get persistentvolume --watch --show-labels'
alias kgallwoyaml='kubectl get --all-namespaces --watch -o=yaml'
alias kgpoallwoyaml='kubectl get pods --all-namespaces --watch -o=yaml'
alias kgevallwoyaml='kubectl get events --all-namespaces --watch -o=yaml'
alias kgdepallwoyaml='kubectl get deployment --all-namespaces --watch -o=yaml'
alias kgsvcallwoyaml='kubectl get service --all-namespaces --watch -o=yaml'
alias kgingallwoyaml='kubectl get ingress --all-namespaces --watch -o=yaml'
alias kgcmallwoyaml='kubectl get configmap --all-namespaces --watch -o=yaml'
alias kgsecallwoyaml='kubectl get secret --all-namespaces --watch -o=yaml'
alias kgnsallwoyaml='kubectl get namespaces --all-namespaces --watch -o=yaml'
alias kgpvcallwoyaml='kubectl get persistentvolumeclaim --all-namespaces --watch -o=yaml'
alias kgpvallwoyaml='kubectl get persistentvolume --all-namespaces --watch -o=yaml'
alias kgwoyamlall='kubectl get --watch -o=yaml --all-namespaces'
alias kgpowoyamlall='kubectl get pods --watch -o=yaml --all-namespaces'
alias kgevwoyamlall='kubectl get events --watch -o=yaml --all-namespaces'
alias kgdepwoyamlall='kubectl get deployment --watch -o=yaml --all-namespaces'
alias kgsvcwoyamlall='kubectl get service --watch -o=yaml --all-namespaces'
alias kgingwoyamlall='kubectl get ingress --watch -o=yaml --all-namespaces'
alias kgcmwoyamlall='kubectl get configmap --watch -o=yaml --all-namespaces'
alias kgsecwoyamlall='kubectl get secret --watch -o=yaml --all-namespaces'
alias kgnswoyamlall='kubectl get namespaces --watch -o=yaml --all-namespaces'
alias kgpvcwoyamlall='kubectl get persistentvolumeclaim --watch -o=yaml --all-namespaces'
alias kgpvwoyamlall='kubectl get persistentvolume --watch -o=yaml --all-namespaces'
alias kgwalloyaml='kubectl get --watch --all-namespaces -o=yaml'
alias kgpowalloyaml='kubectl get pods --watch --all-namespaces -o=yaml'
alias kgevwalloyaml='kubectl get events --watch --all-namespaces -o=yaml'
alias kgdepwalloyaml='kubectl get deployment --watch --all-namespaces -o=yaml'
alias kgsvcwalloyaml='kubectl get service --watch --all-namespaces -o=yaml'
alias kgingwalloyaml='kubectl get ingress --watch --all-namespaces -o=yaml'
alias kgcmwalloyaml='kubectl get configmap --watch --all-namespaces -o=yaml'
alias kgsecwalloyaml='kubectl get secret --watch --all-namespaces -o=yaml'
alias kgnswalloyaml='kubectl get namespaces --watch --all-namespaces -o=yaml'
alias kgpvcwalloyaml='kubectl get persistentvolumeclaim --watch --all-namespaces -o=yaml'
alias kgpvwalloyaml='kubectl get persistentvolume --watch --all-namespaces -o=yaml'
alias kgowideallsl='kubectl get -o=wide --all-namespaces --show-labels'
alias kgpoowideallsl='kubectl get pods -o=wide --all-namespaces --show-labels'
alias kgdepowideallsl='kubectl get deployment -o=wide --all-namespaces --show-labels'
alias kgsecowideallsl='kubectl get secret -o=wide --all-namespaces --show-labels'
alias kgpvcowideallsl='kubectl get persistentvolumeclaim -o=wide --all-namespaces --show-labels'
alias kgpvowideallsl='kubectl get persistentvolume -o=wide --all-namespaces --show-labels'
alias kgowideslall='kubectl get -o=wide --show-labels --all-namespaces'
alias kgpoowideslall='kubectl get pods -o=wide --show-labels --all-namespaces'
alias kgdepowideslall='kubectl get deployment -o=wide --show-labels --all-namespaces'
alias kgsecowideslall='kubectl get secret -o=wide --show-labels --all-namespaces'
alias kgpvcowideslall='kubectl get persistentvolumeclaim -o=wide --show-labels --all-namespaces'
alias kgpvowideslall='kubectl get persistentvolume -o=wide --show-labels --all-namespaces'
alias kgallowidesl='kubectl get --all-namespaces -o=wide --show-labels'
alias kgpoallowidesl='kubectl get pods --all-namespaces -o=wide --show-labels'
alias kgdepallowidesl='kubectl get deployment --all-namespaces -o=wide --show-labels'
alias kgsecallowidesl='kubectl get secret --all-namespaces -o=wide --show-labels'
alias kgpvcallowidesl='kubectl get persistentvolumeclaim --all-namespaces -o=wide --show-labels'
alias kgpvallowidesl='kubectl get persistentvolume --all-namespaces -o=wide --show-labels'
alias kgallslowide='kubectl get --all-namespaces --show-labels -o=wide'
alias kgpoallslowide='kubectl get pods --all-namespaces --show-labels -o=wide'
alias kgdepallslowide='kubectl get deployment --all-namespaces --show-labels -o=wide'
alias kgsecallslowide='kubectl get secret --all-namespaces --show-labels -o=wide'
alias kgpvcallslowide='kubectl get persistentvolumeclaim --all-namespaces --show-labels -o=wide'
alias kgpvallslowide='kubectl get persistentvolume --all-namespaces --show-labels -o=wide'
alias kgslowideall='kubectl get --show-labels -o=wide --all-namespaces'
alias kgposlowideall='kubectl get pods --show-labels -o=wide --all-namespaces'
alias kgdepslowideall='kubectl get deployment --show-labels -o=wide --all-namespaces'
alias kgsecslowideall='kubectl get secret --show-labels -o=wide --all-namespaces'
alias kgpvcslowideall='kubectl get persistentvolumeclaim --show-labels -o=wide --all-namespaces'
alias kgpvslowideall='kubectl get persistentvolume --show-labels -o=wide --all-namespaces'
alias kgslallowide='kubectl get --show-labels --all-namespaces -o=wide'
alias kgposlallowide='kubectl get pods --show-labels --all-namespaces -o=wide'
alias kgdepslallowide='kubectl get deployment --show-labels --all-namespaces -o=wide'
alias kgsecslallowide='kubectl get secret --show-labels --all-namespaces -o=wide'
alias kgpvcslallowide='kubectl get persistentvolumeclaim --show-labels --all-namespaces -o=wide'
alias kgpvslallowide='kubectl get persistentvolume --show-labels --all-namespaces -o=wide'
alias kgallwowide='kubectl get --all-namespaces --watch -o=wide'
alias kgpoallwowide='kubectl get pods --all-namespaces --watch -o=wide'
alias kgevallwowide='kubectl get events --all-namespaces --watch -o=wide'
alias kgdepallwowide='kubectl get deployment --all-namespaces --watch -o=wide'
alias kgsvcallwowide='kubectl get service --all-namespaces --watch -o=wide'
alias kgingallwowide='kubectl get ingress --all-namespaces --watch -o=wide'
alias kgcmallwowide='kubectl get configmap --all-namespaces --watch -o=wide'
alias kgsecallwowide='kubectl get secret --all-namespaces --watch -o=wide'
alias kgnsallwowide='kubectl get namespaces --all-namespaces --watch -o=wide'
alias kgpvcallwowide='kubectl get persistentvolumeclaim --all-namespaces --watch -o=wide'
alias kgpvallwowide='kubectl get persistentvolume --all-namespaces --watch -o=wide'
alias kgwowideall='kubectl get --watch -o=wide --all-namespaces'
alias kgpowowideall='kubectl get pods --watch -o=wide --all-namespaces'
alias kgevwowideall='kubectl get events --watch -o=wide --all-namespaces'
alias kgdepwowideall='kubectl get deployment --watch -o=wide --all-namespaces'
alias kgsvcwowideall='kubectl get service --watch -o=wide --all-namespaces'
alias kgingwowideall='kubectl get ingress --watch -o=wide --all-namespaces'
alias kgcmwowideall='kubectl get configmap --watch -o=wide --all-namespaces'
alias kgsecwowideall='kubectl get secret --watch -o=wide --all-namespaces'
alias kgnswowideall='kubectl get namespaces --watch -o=wide --all-namespaces'
alias kgpvcwowideall='kubectl get persistentvolumeclaim --watch -o=wide --all-namespaces'
alias kgpvwowideall='kubectl get persistentvolume --watch -o=wide --all-namespaces'
alias kgwallowide='kubectl get --watch --all-namespaces -o=wide'
alias kgpowallowide='kubectl get pods --watch --all-namespaces -o=wide'
alias kgevwallowide='kubectl get events --watch --all-namespaces -o=wide'
alias kgdepwallowide='kubectl get deployment --watch --all-namespaces -o=wide'
alias kgsvcwallowide='kubectl get service --watch --all-namespaces -o=wide'
alias kgingwallowide='kubectl get ingress --watch --all-namespaces -o=wide'
alias kgcmwallowide='kubectl get configmap --watch --all-namespaces -o=wide'
alias kgsecwallowide='kubectl get secret --watch --all-namespaces -o=wide'
alias kgnswallowide='kubectl get namespaces --watch --all-namespaces -o=wide'
alias kgpvcwallowide='kubectl get persistentvolumeclaim --watch --all-namespaces -o=wide'
alias kgpvwallowide='kubectl get persistentvolume --watch --all-namespaces -o=wide'
alias kgslwowide='kubectl get --show-labels --watch -o=wide'
alias ksysgslwowide='kubectl --namespace=kube-system get --show-labels --watch -o=wide'
alias kgposlwowide='kubectl get pods --show-labels --watch -o=wide'
alias ksysgposlwowide='kubectl --namespace=kube-system get pods --show-labels --watch -o=wide'
alias kgdepslwowide='kubectl get deployment --show-labels --watch -o=wide'
alias ksysgdepslwowide='kubectl --namespace=kube-system get deployment --show-labels --watch -o=wide'
alias kgsecslwowide='kubectl get secret --show-labels --watch -o=wide'
alias ksysgsecslwowide='kubectl --namespace=kube-system get secret --show-labels --watch -o=wide'
alias kgnoslwowide='kubectl get nodes --show-labels --watch -o=wide'
alias kgpvcslwowide='kubectl get persistentvolumeclaim --show-labels --watch -o=wide'
alias ksysgpvcslwowide='kubectl --namespace=kube-system get persistentvolumeclaim --show-labels --watch -o=wide'
alias kgpvslwowide='kubectl get persistentvolume --show-labels --watch -o=wide'
alias ksysgpvslwowide='kubectl --namespace=kube-system get persistentvolume --show-labels --watch -o=wide'
alias kgwowidesl='kubectl get --watch -o=wide --show-labels'
alias ksysgwowidesl='kubectl --namespace=kube-system get --watch -o=wide --show-labels'
alias kgpowowidesl='kubectl get pods --watch -o=wide --show-labels'
alias ksysgpowowidesl='kubectl --namespace=kube-system get pods --watch -o=wide --show-labels'
alias kgdepwowidesl='kubectl get deployment --watch -o=wide --show-labels'
alias ksysgdepwowidesl='kubectl --namespace=kube-system get deployment --watch -o=wide --show-labels'
alias kgsecwowidesl='kubectl get secret --watch -o=wide --show-labels'
alias ksysgsecwowidesl='kubectl --namespace=kube-system get secret --watch -o=wide --show-labels'
alias kgnowowidesl='kubectl get nodes --watch -o=wide --show-labels'
alias kgpvcwowidesl='kubectl get persistentvolumeclaim --watch -o=wide --show-labels'
alias ksysgpvcwowidesl='kubectl --namespace=kube-system get persistentvolumeclaim --watch -o=wide --show-labels'
alias kgpvwowidesl='kubectl get persistentvolume --watch -o=wide --show-labels'
alias ksysgpvwowidesl='kubectl --namespace=kube-system get persistentvolume --watch -o=wide --show-labels'
alias kgwslowide='kubectl get --watch --show-labels -o=wide'
alias ksysgwslowide='kubectl --namespace=kube-system get --watch --show-labels -o=wide'
alias kgpowslowide='kubectl get pods --watch --show-labels -o=wide'
alias ksysgpowslowide='kubectl --namespace=kube-system get pods --watch --show-labels -o=wide'
alias kgdepwslowide='kubectl get deployment --watch --show-labels -o=wide'
alias ksysgdepwslowide='kubectl --namespace=kube-system get deployment --watch --show-labels -o=wide'
alias kgsecwslowide='kubectl get secret --watch --show-labels -o=wide'
alias ksysgsecwslowide='kubectl --namespace=kube-system get secret --watch --show-labels -o=wide'
alias kgnowslowide='kubectl get nodes --watch --show-labels -o=wide'
alias kgpvcwslowide='kubectl get persistentvolumeclaim --watch --show-labels -o=wide'
alias ksysgpvcwslowide='kubectl --namespace=kube-system get persistentvolumeclaim --watch --show-labels -o=wide'
alias kgpvwslowide='kubectl get persistentvolume --watch --show-labels -o=wide'
alias ksysgpvwslowide='kubectl --namespace=kube-system get persistentvolume --watch --show-labels -o=wide'
alias kgallslw='kubectl get --all-namespaces --show-labels --watch'
alias kgpoallslw='kubectl get pods --all-namespaces --show-labels --watch'
alias kgdepallslw='kubectl get deployment --all-namespaces --show-labels --watch'
alias kgsecallslw='kubectl get secret --all-namespaces --show-labels --watch'
alias kgpvcallslw='kubectl get persistentvolumeclaim --all-namespaces --show-labels --watch'
alias kgpvallslw='kubectl get persistentvolume --all-namespaces --show-labels --watch'
alias kgallwsl='kubectl get --all-namespaces --watch --show-labels'
alias kgpoallwsl='kubectl get pods --all-namespaces --watch --show-labels'
alias kgdepallwsl='kubectl get deployment --all-namespaces --watch --show-labels'
alias kgsecallwsl='kubectl get secret --all-namespaces --watch --show-labels'
alias kgpvcallwsl='kubectl get persistentvolumeclaim --all-namespaces --watch --show-labels'
alias kgpvallwsl='kubectl get persistentvolume --all-namespaces --watch --show-labels'
alias kgslallw='kubectl get --show-labels --all-namespaces --watch'
alias kgposlallw='kubectl get pods --show-labels --all-namespaces --watch'
alias kgdepslallw='kubectl get deployment --show-labels --all-namespaces --watch'
alias kgsecslallw='kubectl get secret --show-labels --all-namespaces --watch'
alias kgpvcslallw='kubectl get persistentvolumeclaim --show-labels --all-namespaces --watch'
alias kgpvslallw='kubectl get persistentvolume --show-labels --all-namespaces --watch'
alias kgslwall='kubectl get --show-labels --watch --all-namespaces'
alias kgposlwall='kubectl get pods --show-labels --watch --all-namespaces'
alias kgdepslwall='kubectl get deployment --show-labels --watch --all-namespaces'
alias kgsecslwall='kubectl get secret --show-labels --watch --all-namespaces'
alias kgpvcslwall='kubectl get persistentvolumeclaim --show-labels --watch --all-namespaces'
alias kgpvslwall='kubectl get persistentvolume --show-labels --watch --all-namespaces'
alias kgwallsl='kubectl get --watch --all-namespaces --show-labels'
alias kgpowallsl='kubectl get pods --watch --all-namespaces --show-labels'
alias kgdepwallsl='kubectl get deployment --watch --all-namespaces --show-labels'
alias kgsecwallsl='kubectl get secret --watch --all-namespaces --show-labels'
alias kgpvcwallsl='kubectl get persistentvolumeclaim --watch --all-namespaces --show-labels'
alias kgpvwallsl='kubectl get persistentvolume --watch --all-namespaces --show-labels'
alias kgwslall='kubectl get --watch --show-labels --all-namespaces'
alias kgpowslall='kubectl get pods --watch --show-labels --all-namespaces'
alias kgdepwslall='kubectl get deployment --watch --show-labels --all-namespaces'
alias kgsecwslall='kubectl get secret --watch --show-labels --all-namespaces'
alias kgpvcwslall='kubectl get persistentvolumeclaim --watch --show-labels --all-namespaces'
alias kgpvwslall='kubectl get persistentvolume --watch --show-labels --all-namespaces'
alias kgallslwowide='kubectl get --all-namespaces --show-labels --watch -o=wide'
alias kgpoallslwowide='kubectl get pods --all-namespaces --show-labels --watch -o=wide'
alias kgdepallslwowide='kubectl get deployment --all-namespaces --show-labels --watch -o=wide'
alias kgsecallslwowide='kubectl get secret --all-namespaces --show-labels --watch -o=wide'
alias kgpvcallslwowide='kubectl get persistentvolumeclaim --all-namespaces --show-labels --watch -o=wide'
alias kgpvallslwowide='kubectl get persistentvolume --all-namespaces --show-labels --watch -o=wide'
alias kgallwowidesl='kubectl get --all-namespaces --watch -o=wide --show-labels'
alias kgpoallwowidesl='kubectl get pods --all-namespaces --watch -o=wide --show-labels'
alias kgdepallwowidesl='kubectl get deployment --all-namespaces --watch -o=wide --show-labels'
alias kgsecallwowidesl='kubectl get secret --all-namespaces --watch -o=wide --show-labels'
alias kgpvcallwowidesl='kubectl get persistentvolumeclaim --all-namespaces --watch -o=wide --show-labels'
alias kgpvallwowidesl='kubectl get persistentvolume --all-namespaces --watch -o=wide --show-labels'
alias kgallwslowide='kubectl get --all-namespaces --watch --show-labels -o=wide'
alias kgpoallwslowide='kubectl get pods --all-namespaces --watch --show-labels -o=wide'
alias kgdepallwslowide='kubectl get deployment --all-namespaces --watch --show-labels -o=wide'
alias kgsecallwslowide='kubectl get secret --all-namespaces --watch --show-labels -o=wide'
alias kgpvcallwslowide='kubectl get persistentvolumeclaim --all-namespaces --watch --show-labels -o=wide'
alias kgpvallwslowide='kubectl get persistentvolume --all-namespaces --watch --show-labels -o=wide'
alias kgslallwowide='kubectl get --show-labels --all-namespaces --watch -o=wide'
alias kgposlallwowide='kubectl get pods --show-labels --all-namespaces --watch -o=wide'
alias kgdepslallwowide='kubectl get deployment --show-labels --all-namespaces --watch -o=wide'
alias kgsecslallwowide='kubectl get secret --show-labels --all-namespaces --watch -o=wide'
alias kgpvcslallwowide='kubectl get persistentvolumeclaim --show-labels --all-namespaces --watch -o=wide'
alias kgpvslallwowide='kubectl get persistentvolume --show-labels --all-namespaces --watch -o=wide'
alias kgslwowideall='kubectl get --show-labels --watch -o=wide --all-namespaces'
alias kgposlwowideall='kubectl get pods --show-labels --watch -o=wide --all-namespaces'
alias kgdepslwowideall='kubectl get deployment --show-labels --watch -o=wide --all-namespaces'
alias kgsecslwowideall='kubectl get secret --show-labels --watch -o=wide --all-namespaces'
alias kgpvcslwowideall='kubectl get persistentvolumeclaim --show-labels --watch -o=wide --all-namespaces'
alias kgpvslwowideall='kubectl get persistentvolume --show-labels --watch -o=wide --all-namespaces'
alias kgslwallowide='kubectl get --show-labels --watch --all-namespaces -o=wide'
alias kgposlwallowide='kubectl get pods --show-labels --watch --all-namespaces -o=wide'
alias kgdepslwallowide='kubectl get deployment --show-labels --watch --all-namespaces -o=wide'
alias kgsecslwallowide='kubectl get secret --show-labels --watch --all-namespaces -o=wide'
alias kgpvcslwallowide='kubectl get persistentvolumeclaim --show-labels --watch --all-namespaces -o=wide'
alias kgpvslwallowide='kubectl get persistentvolume --show-labels --watch --all-namespaces -o=wide'
alias kgwowideallsl='kubectl get --watch -o=wide --all-namespaces --show-labels'
alias kgpowowideallsl='kubectl get pods --watch -o=wide --all-namespaces --show-labels'
alias kgdepwowideallsl='kubectl get deployment --watch -o=wide --all-namespaces --show-labels'
alias kgsecwowideallsl='kubectl get secret --watch -o=wide --all-namespaces --show-labels'
alias kgpvcwowideallsl='kubectl get persistentvolumeclaim --watch -o=wide --all-namespaces --show-labels'
alias kgpvwowideallsl='kubectl get persistentvolume --watch -o=wide --all-namespaces --show-labels'
alias kgwowideslall='kubectl get --watch -o=wide --show-labels --all-namespaces'
alias kgpowowideslall='kubectl get pods --watch -o=wide --show-labels --all-namespaces'
alias kgdepwowideslall='kubectl get deployment --watch -o=wide --show-labels --all-namespaces'
alias kgsecwowideslall='kubectl get secret --watch -o=wide --show-labels --all-namespaces'
alias kgpvcwowideslall='kubectl get persistentvolumeclaim --watch -o=wide --show-labels --all-namespaces'
alias kgpvwowideslall='kubectl get persistentvolume --watch -o=wide --show-labels --all-namespaces'
alias kgwallowidesl='kubectl get --watch --all-namespaces -o=wide --show-labels'
alias kgpowallowidesl='kubectl get pods --watch --all-namespaces -o=wide --show-labels'
alias kgdepwallowidesl='kubectl get deployment --watch --all-namespaces -o=wide --show-labels'
alias kgsecwallowidesl='kubectl get secret --watch --all-namespaces -o=wide --show-labels'
alias kgpvcwallowidesl='kubectl get persistentvolumeclaim --watch --all-namespaces -o=wide --show-labels'
alias kgpvwallowidesl='kubectl get persistentvolume --watch --all-namespaces -o=wide --show-labels'
alias kgwallslowide='kubectl get --watch --all-namespaces --show-labels -o=wide'
alias kgpowallslowide='kubectl get pods --watch --all-namespaces --show-labels -o=wide'
alias kgdepwallslowide='kubectl get deployment --watch --all-namespaces --show-labels -o=wide'
alias kgsecwallslowide='kubectl get secret --watch --all-namespaces --show-labels -o=wide'
alias kgpvcwallslowide='kubectl get persistentvolumeclaim --watch --all-namespaces --show-labels -o=wide'
alias kgpvwallslowide='kubectl get persistentvolume --watch --all-namespaces --show-labels -o=wide'
alias kgwslowideall='kubectl get --watch --show-labels -o=wide --all-namespaces'
alias kgpowslowideall='kubectl get pods --watch --show-labels -o=wide --all-namespaces'
alias kgdepwslowideall='kubectl get deployment --watch --show-labels -o=wide --all-namespaces'
alias kgsecwslowideall='kubectl get secret --watch --show-labels -o=wide --all-namespaces'
alias kgpvcwslowideall='kubectl get persistentvolumeclaim --watch --show-labels -o=wide --all-namespaces'
alias kgpvwslowideall='kubectl get persistentvolume --watch --show-labels -o=wide --all-namespaces'
alias kgwslallowide='kubectl get --watch --show-labels --all-namespaces -o=wide'
alias kgpowslallowide='kubectl get pods --watch --show-labels --all-namespaces -o=wide'
alias kgdepwslallowide='kubectl get deployment --watch --show-labels --all-namespaces -o=wide'
alias kgsecwslallowide='kubectl get secret --watch --show-labels --all-namespaces -o=wide'
alias kgpvcwslallowide='kubectl get persistentvolumeclaim --watch --show-labels --all-namespaces -o=wide'
alias kgpvwslallowide='kubectl get persistentvolume --watch --show-labels --all-namespaces -o=wide'
alias kgf='kubectl get --recursive -f'
alias kdf='kubectl describe --recursive -f'
alias krmf='kubectl delete --recursive -f'
alias kgoyamlf='kubectl get -o=yaml --recursive -f'
alias kgowidef='kubectl get -o=wide --recursive -f'
alias kgslf='kubectl get --show-labels --recursive -f'
alias kgwf='kubectl get --watch --recursive -f'
alias kgwoyamlf='kubectl get --watch -o=yaml --recursive -f'
alias kgowideslf='kubectl get -o=wide --show-labels --recursive -f'
alias kgslowidef='kubectl get --show-labels -o=wide --recursive -f'
alias kgwowidef='kubectl get --watch -o=wide --recursive -f'
alias kgslwf='kubectl get --show-labels --watch --recursive -f'
alias kgwslf='kubectl get --watch --show-labels --recursive -f'
alias kgslwowidef='kubectl get --show-labels --watch -o=wide --recursive -f'
alias kgwowideslf='kubectl get --watch -o=wide --show-labels --recursive -f'
alias kgwslowidef='kubectl get --watch --show-labels -o=wide --recursive -f'
alias kgl='kubectl get -l'
alias ksysgl='kubectl --namespace=kube-system get -l'
alias kdl='kubectl describe -l'
alias ksysdl='kubectl --namespace=kube-system describe -l'
alias krml='kubectl delete -l'
alias ksysrml='kubectl --namespace=kube-system delete -l'
alias ktl='kubectl top -l'
alias ksystl='kubectl --namespace=kube-system top -l'
alias kgpol='kubectl get pods -l'
alias ksysgpol='kubectl --namespace=kube-system get pods -l'
alias kdpol='kubectl describe pods -l'
alias ksysdpol='kubectl --namespace=kube-system describe pods -l'
alias krmpol='kubectl delete pods -l'
alias ksysrmpol='kubectl --namespace=kube-system delete pods -l'
alias ktpol='kubectl top pods -l'
alias ksystpol='kubectl --namespace=kube-system top pods -l'
alias kgevl='kubectl get events -l'
alias ksysgevl='kubectl --namespace=kube-system get events -l'
alias kdevl='kubectl describe events -l'
alias ksysdevl='kubectl --namespace=kube-system describe events -l'
alias kgdepl='kubectl get deployment -l'
alias ksysgdepl='kubectl --namespace=kube-system get deployment -l'
alias kddepl='kubectl describe deployment -l'
alias ksysddepl='kubectl --namespace=kube-system describe deployment -l'
alias krmdepl='kubectl delete deployment -l'
alias ksysrmdepl='kubectl --namespace=kube-system delete deployment -l'
alias kgsvcl='kubectl get service -l'
alias ksysgsvcl='kubectl --namespace=kube-system get service -l'
alias kdsvcl='kubectl describe service -l'
alias ksysdsvcl='kubectl --namespace=kube-system describe service -l'
alias krmsvcl='kubectl delete service -l'
alias ksysrmsvcl='kubectl --namespace=kube-system delete service -l'
alias kgingl='kubectl get ingress -l'
alias ksysgingl='kubectl --namespace=kube-system get ingress -l'
alias kdingl='kubectl describe ingress -l'
alias ksysdingl='kubectl --namespace=kube-system describe ingress -l'
alias krmingl='kubectl delete ingress -l'
alias ksysrmingl='kubectl --namespace=kube-system delete ingress -l'
alias kgcml='kubectl get configmap -l'
alias ksysgcml='kubectl --namespace=kube-system get configmap -l'
alias kdcml='kubectl describe configmap -l'
alias ksysdcml='kubectl --namespace=kube-system describe configmap -l'
alias krmcml='kubectl delete configmap -l'
alias ksysrmcml='kubectl --namespace=kube-system delete configmap -l'
alias kgsecl='kubectl get secret -l'
alias ksysgsecl='kubectl --namespace=kube-system get secret -l'
alias kdsecl='kubectl describe secret -l'
alias ksysdsecl='kubectl --namespace=kube-system describe secret -l'
alias krmsecl='kubectl delete secret -l'
alias ksysrmsecl='kubectl --namespace=kube-system delete secret -l'
alias kgnol='kubectl get nodes -l'
alias kdnol='kubectl describe nodes -l'
alias ktnol='kubectl top nodes -l'
alias kgnsl='kubectl get namespaces -l'
alias kdnsl='kubectl describe namespaces -l'
alias krmnsl='kubectl delete namespaces -l'
alias kgpvcl='kubectl get persistentvolumeclaim -l'
alias ksysgpvcl='kubectl --namespace=kube-system get persistentvolumeclaim -l'
alias kdpvcl='kubectl describe persistentvolumeclaim -l'
alias ksysdpvcl='kubectl --namespace=kube-system describe persistentvolumeclaim -l'
alias krmpvcl='kubectl delete persistentvolumeclaim -l'
alias ksysrmpvcl='kubectl --namespace=kube-system delete persistentvolumeclaim -l'
alias kgpvl='kubectl get persistentvolume -l'
alias ksysgpvl='kubectl --namespace=kube-system get persistentvolume -l'
alias kdpvl='kubectl describe persistentvolume -l'
alias ksysdpvl='kubectl --namespace=kube-system describe persistentvolume -l'
alias krmpvl='kubectl delete persistentvolume -l'
alias ksysrmpvl='kubectl --namespace=kube-system delete persistentvolume -l'
alias kgoyamll='kubectl get -o=yaml -l'
alias ksysgoyamll='kubectl --namespace=kube-system get -o=yaml -l'
alias kgpooyamll='kubectl get pods -o=yaml -l'
alias ksysgpooyamll='kubectl --namespace=kube-system get pods -o=yaml -l'
alias kgevoyamll='kubectl get events -o=yaml -l'
alias ksysgevoyamll='kubectl --namespace=kube-system get events -o=yaml -l'
alias kgdepoyamll='kubectl get deployment -o=yaml -l'
alias ksysgdepoyamll='kubectl --namespace=kube-system get deployment -o=yaml -l'
alias kgsvcoyamll='kubectl get service -o=yaml -l'
alias ksysgsvcoyamll='kubectl --namespace=kube-system get service -o=yaml -l'
alias kgingoyamll='kubectl get ingress -o=yaml -l'
alias ksysgingoyamll='kubectl --namespace=kube-system get ingress -o=yaml -l'
alias kgcmoyamll='kubectl get configmap -o=yaml -l'
alias ksysgcmoyamll='kubectl --namespace=kube-system get configmap -o=yaml -l'
alias kgsecoyamll='kubectl get secret -o=yaml -l'
alias ksysgsecoyamll='kubectl --namespace=kube-system get secret -o=yaml -l'
alias kgnooyamll='kubectl get nodes -o=yaml -l'
alias kgnsoyamll='kubectl get namespaces -o=yaml -l'
alias kgpvcoyamll='kubectl get persistentvolumeclaim -o=yaml -l'
alias ksysgpvcoyamll='kubectl --namespace=kube-system get persistentvolumeclaim -o=yaml -l'
alias kgpvoyamll='kubectl get persistentvolume -o=yaml -l'
alias ksysgpvoyamll='kubectl --namespace=kube-system get persistentvolume -o=yaml -l'
alias kgowidel='kubectl get -o=wide -l'
alias ksysgowidel='kubectl --namespace=kube-system get -o=wide -l'
alias kgpoowidel='kubectl get pods -o=wide -l'
alias ksysgpoowidel='kubectl --namespace=kube-system get pods -o=wide -l'
alias kgevowidel='kubectl get events -o=wide -l'
alias ksysgevowidel='kubectl --namespace=kube-system get events -o=wide -l'
alias kgdepowidel='kubectl get deployment -o=wide -l'
alias ksysgdepowidel='kubectl --namespace=kube-system get deployment -o=wide -l'
alias kgsvcowidel='kubectl get service -o=wide -l'
alias ksysgsvcowidel='kubectl --namespace=kube-system get service -o=wide -l'
alias kgingowidel='kubectl get ingress -o=wide -l'
alias ksysgingowidel='kubectl --namespace=kube-system get ingress -o=wide -l'
alias kgcmowidel='kubectl get configmap -o=wide -l'
alias ksysgcmowidel='kubectl --namespace=kube-system get configmap -o=wide -l'
alias kgsecowidel='kubectl get secret -o=wide -l'
alias ksysgsecowidel='kubectl --namespace=kube-system get secret -o=wide -l'
alias kgnoowidel='kubectl get nodes -o=wide -l'
alias kgnsowidel='kubectl get namespaces -o=wide -l'
alias kgpvcowidel='kubectl get persistentvolumeclaim -o=wide -l'
alias ksysgpvcowidel='kubectl --namespace=kube-system get persistentvolumeclaim -o=wide -l'
alias kgpvowidel='kubectl get persistentvolume -o=wide -l'
alias ksysgpvowidel='kubectl --namespace=kube-system get persistentvolume -o=wide -l'
alias kgsll='kubectl get --show-labels -l'
alias ksysgsll='kubectl --namespace=kube-system get --show-labels -l'
alias kgposll='kubectl get pods --show-labels -l'
alias ksysgposll='kubectl --namespace=kube-system get pods --show-labels -l'
alias kgdepsll='kubectl get deployment --show-labels -l'
alias ksysgdepsll='kubectl --namespace=kube-system get deployment --show-labels -l'
alias kgsecsll='kubectl get secret --show-labels -l'
alias ksysgsecsll='kubectl --namespace=kube-system get secret --show-labels -l'
alias kgnosll='kubectl get nodes --show-labels -l'
alias kgpvcsll='kubectl get persistentvolumeclaim --show-labels -l'
alias ksysgpvcsll='kubectl --namespace=kube-system get persistentvolumeclaim --show-labels -l'
alias kgpvsll='kubectl get persistentvolume --show-labels -l'
alias ksysgpvsll='kubectl --namespace=kube-system get persistentvolume --show-labels -l'
alias kgwl='kubectl get --watch -l'
alias ksysgwl='kubectl --namespace=kube-system get --watch -l'
alias kgpowl='kubectl get pods --watch -l'
alias ksysgpowl='kubectl --namespace=kube-system get pods --watch -l'
alias kgevwl='kubectl get events --watch -l'
alias ksysgevwl='kubectl --namespace=kube-system get events --watch -l'
alias kgdepwl='kubectl get deployment --watch -l'
alias ksysgdepwl='kubectl --namespace=kube-system get deployment --watch -l'
alias kgsvcwl='kubectl get service --watch -l'
alias ksysgsvcwl='kubectl --namespace=kube-system get service --watch -l'
alias kgingwl='kubectl get ingress --watch -l'
alias ksysgingwl='kubectl --namespace=kube-system get ingress --watch -l'
alias kgcmwl='kubectl get configmap --watch -l'
alias ksysgcmwl='kubectl --namespace=kube-system get configmap --watch -l'
alias kgsecwl='kubectl get secret --watch -l'
alias ksysgsecwl='kubectl --namespace=kube-system get secret --watch -l'
alias kgnowl='kubectl get nodes --watch -l'
alias kgnswl='kubectl get namespaces --watch -l'
alias kgpvcwl='kubectl get persistentvolumeclaim --watch -l'
alias ksysgpvcwl='kubectl --namespace=kube-system get persistentvolumeclaim --watch -l'
alias kgpvwl='kubectl get persistentvolume --watch -l'
alias ksysgpvwl='kubectl --namespace=kube-system get persistentvolume --watch -l'
alias kgwoyamll='kubectl get --watch -o=yaml -l'
alias ksysgwoyamll='kubectl --namespace=kube-system get --watch -o=yaml -l'
alias kgpowoyamll='kubectl get pods --watch -o=yaml -l'
alias ksysgpowoyamll='kubectl --namespace=kube-system get pods --watch -o=yaml -l'
alias kgevwoyamll='kubectl get events --watch -o=yaml -l'
alias ksysgevwoyamll='kubectl --namespace=kube-system get events --watch -o=yaml -l'
alias kgdepwoyamll='kubectl get deployment --watch -o=yaml -l'
alias ksysgdepwoyamll='kubectl --namespace=kube-system get deployment --watch -o=yaml -l'
alias kgsvcwoyamll='kubectl get service --watch -o=yaml -l'
alias ksysgsvcwoyamll='kubectl --namespace=kube-system get service --watch -o=yaml -l'
alias kgingwoyamll='kubectl get ingress --watch -o=yaml -l'
alias ksysgingwoyamll='kubectl --namespace=kube-system get ingress --watch -o=yaml -l'
alias kgcmwoyamll='kubectl get configmap --watch -o=yaml -l'
alias ksysgcmwoyamll='kubectl --namespace=kube-system get configmap --watch -o=yaml -l'
alias kgsecwoyamll='kubectl get secret --watch -o=yaml -l'
alias ksysgsecwoyamll='kubectl --namespace=kube-system get secret --watch -o=yaml -l'
alias kgnowoyamll='kubectl get nodes --watch -o=yaml -l'
alias kgnswoyamll='kubectl get namespaces --watch -o=yaml -l'
alias kgpvcwoyamll='kubectl get persistentvolumeclaim --watch -o=yaml -l'
alias ksysgpvcwoyamll='kubectl --namespace=kube-system get persistentvolumeclaim --watch -o=yaml -l'
alias kgpvwoyamll='kubectl get persistentvolume --watch -o=yaml -l'
alias ksysgpvwoyamll='kubectl --namespace=kube-system get persistentvolume --watch -o=yaml -l'
alias kgowidesll='kubectl get -o=wide --show-labels -l'
alias ksysgowidesll='kubectl --namespace=kube-system get -o=wide --show-labels -l'
alias kgpoowidesll='kubectl get pods -o=wide --show-labels -l'
alias ksysgpoowidesll='kubectl --namespace=kube-system get pods -o=wide --show-labels -l'
alias kgdepowidesll='kubectl get deployment -o=wide --show-labels -l'
alias ksysgdepowidesll='kubectl --namespace=kube-system get deployment -o=wide --show-labels -l'
alias kgsecowidesll='kubectl get secret -o=wide --show-labels -l'
alias ksysgsecowidesll='kubectl --namespace=kube-system get secret -o=wide --show-labels -l'
alias kgnoowidesll='kubectl get nodes -o=wide --show-labels -l'
alias kgpvcowidesll='kubectl get persistentvolumeclaim -o=wide --show-labels -l'
alias ksysgpvcowidesll='kubectl --namespace=kube-system get persistentvolumeclaim -o=wide --show-labels -l'
alias kgpvowidesll='kubectl get persistentvolume -o=wide --show-labels -l'
alias ksysgpvowidesll='kubectl --namespace=kube-system get persistentvolume -o=wide --show-labels -l'
alias kgslowidel='kubectl get --show-labels -o=wide -l'
alias ksysgslowidel='kubectl --namespace=kube-system get --show-labels -o=wide -l'
alias kgposlowidel='kubectl get pods --show-labels -o=wide -l'
alias ksysgposlowidel='kubectl --namespace=kube-system get pods --show-labels -o=wide -l'
alias kgdepslowidel='kubectl get deployment --show-labels -o=wide -l'
alias ksysgdepslowidel='kubectl --namespace=kube-system get deployment --show-labels -o=wide -l'
alias kgsecslowidel='kubectl get secret --show-labels -o=wide -l'
alias ksysgsecslowidel='kubectl --namespace=kube-system get secret --show-labels -o=wide -l'
alias kgnoslowidel='kubectl get nodes --show-labels -o=wide -l'
alias kgpvcslowidel='kubectl get persistentvolumeclaim --show-labels -o=wide -l'
alias ksysgpvcslowidel='kubectl --namespace=kube-system get persistentvolumeclaim --show-labels -o=wide -l'
alias kgpvslowidel='kubectl get persistentvolume --show-labels -o=wide -l'
alias ksysgpvslowidel='kubectl --namespace=kube-system get persistentvolume --show-labels -o=wide -l'
alias kgwowidel='kubectl get --watch -o=wide -l'
alias ksysgwowidel='kubectl --namespace=kube-system get --watch -o=wide -l'
alias kgpowowidel='kubectl get pods --watch -o=wide -l'
alias ksysgpowowidel='kubectl --namespace=kube-system get pods --watch -o=wide -l'
alias kgevwowidel='kubectl get events --watch -o=wide -l'
alias ksysgevwowidel='kubectl --namespace=kube-system get events --watch -o=wide -l'
alias kgdepwowidel='kubectl get deployment --watch -o=wide -l'
alias ksysgdepwowidel='kubectl --namespace=kube-system get deployment --watch -o=wide -l'
alias kgsvcwowidel='kubectl get service --watch -o=wide -l'
alias ksysgsvcwowidel='kubectl --namespace=kube-system get service --watch -o=wide -l'
alias kgingwowidel='kubectl get ingress --watch -o=wide -l'
alias ksysgingwowidel='kubectl --namespace=kube-system get ingress --watch -o=wide -l'
alias kgcmwowidel='kubectl get configmap --watch -o=wide -l'
alias ksysgcmwowidel='kubectl --namespace=kube-system get configmap --watch -o=wide -l'
alias kgsecwowidel='kubectl get secret --watch -o=wide -l'
alias ksysgsecwowidel='kubectl --namespace=kube-system get secret --watch -o=wide -l'
alias kgnowowidel='kubectl get nodes --watch -o=wide -l'
alias kgnswowidel='kubectl get namespaces --watch -o=wide -l'
alias kgpvcwowidel='kubectl get persistentvolumeclaim --watch -o=wide -l'
alias ksysgpvcwowidel='kubectl --namespace=kube-system get persistentvolumeclaim --watch -o=wide -l'
alias kgpvwowidel='kubectl get persistentvolume --watch -o=wide -l'
alias ksysgpvwowidel='kubectl --namespace=kube-system get persistentvolume --watch -o=wide -l'
alias kgslwl='kubectl get --show-labels --watch -l'
alias ksysgslwl='kubectl --namespace=kube-system get --show-labels --watch -l'
alias kgposlwl='kubectl get pods --show-labels --watch -l'
alias ksysgposlwl='kubectl --namespace=kube-system get pods --show-labels --watch -l'
alias kgdepslwl='kubectl get deployment --show-labels --watch -l'
alias ksysgdepslwl='kubectl --namespace=kube-system get deployment --show-labels --watch -l'
alias kgsecslwl='kubectl get secret --show-labels --watch -l'
alias ksysgsecslwl='kubectl --namespace=kube-system get secret --show-labels --watch -l'
alias kgnoslwl='kubectl get nodes --show-labels --watch -l'
alias kgpvcslwl='kubectl get persistentvolumeclaim --show-labels --watch -l'
alias ksysgpvcslwl='kubectl --namespace=kube-system get persistentvolumeclaim --show-labels --watch -l'
alias kgpvslwl='kubectl get persistentvolume --show-labels --watch -l'
alias ksysgpvslwl='kubectl --namespace=kube-system get persistentvolume --show-labels --watch -l'
alias kgwsll='kubectl get --watch --show-labels -l'
alias ksysgwsll='kubectl --namespace=kube-system get --watch --show-labels -l'
alias kgpowsll='kubectl get pods --watch --show-labels -l'
alias ksysgpowsll='kubectl --namespace=kube-system get pods --watch --show-labels -l'
alias kgdepwsll='kubectl get deployment --watch --show-labels -l'
alias ksysgdepwsll='kubectl --namespace=kube-system get deployment --watch --show-labels -l'
alias kgsecwsll='kubectl get secret --watch --show-labels -l'
alias ksysgsecwsll='kubectl --namespace=kube-system get secret --watch --show-labels -l'
alias kgnowsll='kubectl get nodes --watch --show-labels -l'
alias kgpvcwsll='kubectl get persistentvolumeclaim --watch --show-labels -l'
alias ksysgpvcwsll='kubectl --namespace=kube-system get persistentvolumeclaim --watch --show-labels -l'
alias kgpvwsll='kubectl get persistentvolume --watch --show-labels -l'
alias ksysgpvwsll='kubectl --namespace=kube-system get persistentvolume --watch --show-labels -l'
alias kgslwowidel='kubectl get --show-labels --watch -o=wide -l'
alias ksysgslwowidel='kubectl --namespace=kube-system get --show-labels --watch -o=wide -l'
alias kgposlwowidel='kubectl get pods --show-labels --watch -o=wide -l'
alias ksysgposlwowidel='kubectl --namespace=kube-system get pods --show-labels --watch -o=wide -l'
alias kgdepslwowidel='kubectl get deployment --show-labels --watch -o=wide -l'
alias ksysgdepslwowidel='kubectl --namespace=kube-system get deployment --show-labels --watch -o=wide -l'
alias kgsecslwowidel='kubectl get secret --show-labels --watch -o=wide -l'
alias ksysgsecslwowidel='kubectl --namespace=kube-system get secret --show-labels --watch -o=wide -l'
alias kgnoslwowidel='kubectl get nodes --show-labels --watch -o=wide -l'
alias kgpvcslwowidel='kubectl get persistentvolumeclaim --show-labels --watch -o=wide -l'
alias ksysgpvcslwowidel='kubectl --namespace=kube-system get persistentvolumeclaim --show-labels --watch -o=wide -l'
alias kgpvslwowidel='kubectl get persistentvolume --show-labels --watch -o=wide -l'
alias ksysgpvslwowidel='kubectl --namespace=kube-system get persistentvolume --show-labels --watch -o=wide -l'
alias kgwowidesll='kubectl get --watch -o=wide --show-labels -l'
alias ksysgwowidesll='kubectl --namespace=kube-system get --watch -o=wide --show-labels -l'
alias kgpowowidesll='kubectl get pods --watch -o=wide --show-labels -l'
alias ksysgpowowidesll='kubectl --namespace=kube-system get pods --watch -o=wide --show-labels -l'
alias kgdepwowidesll='kubectl get deployment --watch -o=wide --show-labels -l'
alias ksysgdepwowidesll='kubectl --namespace=kube-system get deployment --watch -o=wide --show-labels -l'
alias kgsecwowidesll='kubectl get secret --watch -o=wide --show-labels -l'
alias ksysgsecwowidesll='kubectl --namespace=kube-system get secret --watch -o=wide --show-labels -l'
alias kgnowowidesll='kubectl get nodes --watch -o=wide --show-labels -l'
alias kgpvcwowidesll='kubectl get persistentvolumeclaim --watch -o=wide --show-labels -l'
alias ksysgpvcwowidesll='kubectl --namespace=kube-system get persistentvolumeclaim --watch -o=wide --show-labels -l'
alias kgpvwowidesll='kubectl get persistentvolume --watch -o=wide --show-labels -l'
alias ksysgpvwowidesll='kubectl --namespace=kube-system get persistentvolume --watch -o=wide --show-labels -l'
alias kgwslowidel='kubectl get --watch --show-labels -o=wide -l'
alias ksysgwslowidel='kubectl --namespace=kube-system get --watch --show-labels -o=wide -l'
alias kgpowslowidel='kubectl get pods --watch --show-labels -o=wide -l'
alias ksysgpowslowidel='kubectl --namespace=kube-system get pods --watch --show-labels -o=wide -l'
alias kgdepwslowidel='kubectl get deployment --watch --show-labels -o=wide -l'
alias ksysgdepwslowidel='kubectl --namespace=kube-system get deployment --watch --show-labels -o=wide -l'
alias kgsecwslowidel='kubectl get secret --watch --show-labels -o=wide -l'
alias ksysgsecwslowidel='kubectl --namespace=kube-system get secret --watch --show-labels -o=wide -l'
alias kgnowslowidel='kubectl get nodes --watch --show-labels -o=wide -l'
alias kgpvcwslowidel='kubectl get persistentvolumeclaim --watch --show-labels -o=wide -l'
alias ksysgpvcwslowidel='kubectl --namespace=kube-system get persistentvolumeclaim --watch --show-labels -o=wide -l'
alias kgpvwslowidel='kubectl get persistentvolume --watch --show-labels -o=wide -l'
alias ksysgpvwslowidel='kubectl --namespace=kube-system get persistentvolume --watch --show-labels -o=wide -l'
alias kexn='kubectl exec -i -t --namespace'
alias kedn='kubectl edit --namespace'
alias klon='kubectl logs -f --namespace'
alias kgn='kubectl get --namespace'
alias kdn='kubectl describe --namespace'
alias krmn='kubectl delete --namespace'
alias kpfn='kubectl port-forward --namespace'
alias kedpon='kubectl edit pods --namespace'
alias kgpon='kubectl get pods --namespace'
alias kdpon='kubectl describe pods --namespace'
alias krmpon='kubectl delete pods --namespace'
alias kgevn='kubectl get events --namespace'
alias kdevn='kubectl describe events --namespace'
alias keddepn='kubectl edit deployment --namespace'
alias kgdepn='kubectl get deployment --namespace'
alias kddepn='kubectl describe deployment --namespace'
alias krmdepn='kubectl delete deployment --namespace'
alias kedsvcn='kubectl edit service --namespace'
alias kgsvcn='kubectl get service --namespace'
alias kdsvcn='kubectl describe service --namespace'
alias krmsvcn='kubectl delete service --namespace'
alias kedingn='kubectl edit ingress --namespace'
alias kgingn='kubectl get ingress --namespace'
alias kdingn='kubectl describe ingress --namespace'
alias krmingn='kubectl delete ingress --namespace'
alias kedcmn='kubectl edit configmap --namespace'
alias kgcmn='kubectl get configmap --namespace'
alias kdcmn='kubectl describe configmap --namespace'
alias krmcmn='kubectl delete configmap --namespace'
alias kedsecn='kubectl edit secret --namespace'
alias kgsecn='kubectl get secret --namespace'
alias kdsecn='kubectl describe secret --namespace'
alias krmsecn='kubectl delete secret --namespace'
alias kedpvcn='kubectl edit persistentvolumeclaim --namespace'
alias kgpvcn='kubectl get persistentvolumeclaim --namespace'
alias kdpvcn='kubectl describe persistentvolumeclaim --namespace'
alias krmpvcn='kubectl delete persistentvolumeclaim --namespace'
alias kedpvn='kubectl edit persistentvolume --namespace'
alias kgpvn='kubectl get persistentvolume --namespace'
alias kdpvn='kubectl describe persistentvolume --namespace'
alias krmpvn='kubectl delete persistentvolume --namespace'
alias kgoyamln='kubectl get -o=yaml --namespace'
alias kgpooyamln='kubectl get pods -o=yaml --namespace'
alias kgevoyamln='kubectl get events -o=yaml --namespace'
alias kgdepoyamln='kubectl get deployment -o=yaml --namespace'
alias kgsvcoyamln='kubectl get service -o=yaml --namespace'
alias kgingoyamln='kubectl get ingress -o=yaml --namespace'
alias kgcmoyamln='kubectl get configmap -o=yaml --namespace'
alias kgsecoyamln='kubectl get secret -o=yaml --namespace'
alias kgpvcoyamln='kubectl get persistentvolumeclaim -o=yaml --namespace'
alias kgpvoyamln='kubectl get persistentvolume -o=yaml --namespace'
alias kgowiden='kubectl get -o=wide --namespace'
alias kgpoowiden='kubectl get pods -o=wide --namespace'
alias kgevowiden='kubectl get events -o=wide --namespace'
alias kgdepowiden='kubectl get deployment -o=wide --namespace'
alias kgsvcowiden='kubectl get service -o=wide --namespace'
alias kgingowiden='kubectl get ingress -o=wide --namespace'
alias kgcmowiden='kubectl get configmap -o=wide --namespace'
alias kgsecowiden='kubectl get secret -o=wide --namespace'
alias kgpvcowiden='kubectl get persistentvolumeclaim -o=wide --namespace'
alias kgpvowiden='kubectl get persistentvolume -o=wide --namespace'
alias kgsln='kubectl get --show-labels --namespace'
alias kgposln='kubectl get pods --show-labels --namespace'
alias kgdepsln='kubectl get deployment --show-labels --namespace'
alias kgsecsln='kubectl get secret --show-labels --namespace'
alias kgpvcsln='kubectl get persistentvolumeclaim --show-labels --namespace'
alias kgpvsln='kubectl get persistentvolume --show-labels --namespace'
alias kgwn='kubectl get --watch --namespace'
alias kgpown='kubectl get pods --watch --namespace'
alias kgevwn='kubectl get events --watch --namespace'
alias kgdepwn='kubectl get deployment --watch --namespace'
alias kgsvcwn='kubectl get service --watch --namespace'
alias kgingwn='kubectl get ingress --watch --namespace'
alias kgcmwn='kubectl get configmap --watch --namespace'
alias kgsecwn='kubectl get secret --watch --namespace'
alias kgpvcwn='kubectl get persistentvolumeclaim --watch --namespace'
alias kgpvwn='kubectl get persistentvolume --watch --namespace'
alias kgwoyamln='kubectl get --watch -o=yaml --namespace'
alias kgpowoyamln='kubectl get pods --watch -o=yaml --namespace'
alias kgevwoyamln='kubectl get events --watch -o=yaml --namespace'
alias kgdepwoyamln='kubectl get deployment --watch -o=yaml --namespace'
alias kgsvcwoyamln='kubectl get service --watch -o=yaml --namespace'
alias kgingwoyamln='kubectl get ingress --watch -o=yaml --namespace'
alias kgcmwoyamln='kubectl get configmap --watch -o=yaml --namespace'
alias kgsecwoyamln='kubectl get secret --watch -o=yaml --namespace'
alias kgpvcwoyamln='kubectl get persistentvolumeclaim --watch -o=yaml --namespace'
alias kgpvwoyamln='kubectl get persistentvolume --watch -o=yaml --namespace'
alias kgowidesln='kubectl get -o=wide --show-labels --namespace'
alias kgpoowidesln='kubectl get pods -o=wide --show-labels --namespace'
alias kgdepowidesln='kubectl get deployment -o=wide --show-labels --namespace'
alias kgsecowidesln='kubectl get secret -o=wide --show-labels --namespace'
alias kgpvcowidesln='kubectl get persistentvolumeclaim -o=wide --show-labels --namespace'
alias kgpvowidesln='kubectl get persistentvolume -o=wide --show-labels --namespace'
alias kgslowiden='kubectl get --show-labels -o=wide --namespace'
alias kgposlowiden='kubectl get pods --show-labels -o=wide --namespace'
alias kgdepslowiden='kubectl get deployment --show-labels -o=wide --namespace'
alias kgsecslowiden='kubectl get secret --show-labels -o=wide --namespace'
alias kgpvcslowiden='kubectl get persistentvolumeclaim --show-labels -o=wide --namespace'
alias kgpvslowiden='kubectl get persistentvolume --show-labels -o=wide --namespace'
alias kgwowiden='kubectl get --watch -o=wide --namespace'
alias kgpowowiden='kubectl get pods --watch -o=wide --namespace'
alias kgevwowiden='kubectl get events --watch -o=wide --namespace'
alias kgdepwowiden='kubectl get deployment --watch -o=wide --namespace'
alias kgsvcwowiden='kubectl get service --watch -o=wide --namespace'
alias kgingwowiden='kubectl get ingress --watch -o=wide --namespace'
alias kgcmwowiden='kubectl get configmap --watch -o=wide --namespace'
alias kgsecwowiden='kubectl get secret --watch -o=wide --namespace'
alias kgpvcwowiden='kubectl get persistentvolumeclaim --watch -o=wide --namespace'
alias kgpvwowiden='kubectl get persistentvolume --watch -o=wide --namespace'
alias kgslwn='kubectl get --show-labels --watch --namespace'
alias kgposlwn='kubectl get pods --show-labels --watch --namespace'
alias kgdepslwn='kubectl get deployment --show-labels --watch --namespace'
alias kgsecslwn='kubectl get secret --show-labels --watch --namespace'
alias kgpvcslwn='kubectl get persistentvolumeclaim --show-labels --watch --namespace'
alias kgpvslwn='kubectl get persistentvolume --show-labels --watch --namespace'
alias kgwsln='kubectl get --watch --show-labels --namespace'
alias kgpowsln='kubectl get pods --watch --show-labels --namespace'
alias kgdepwsln='kubectl get deployment --watch --show-labels --namespace'
alias kgsecwsln='kubectl get secret --watch --show-labels --namespace'
alias kgpvcwsln='kubectl get persistentvolumeclaim --watch --show-labels --namespace'
alias kgpvwsln='kubectl get persistentvolume --watch --show-labels --namespace'
alias kgslwowiden='kubectl get --show-labels --watch -o=wide --namespace'
alias kgposlwowiden='kubectl get pods --show-labels --watch -o=wide --namespace'
alias kgdepslwowiden='kubectl get deployment --show-labels --watch -o=wide --namespace'
alias kgsecslwowiden='kubectl get secret --show-labels --watch -o=wide --namespace'
alias kgpvcslwowiden='kubectl get persistentvolumeclaim --show-labels --watch -o=wide --namespace'
alias kgpvslwowiden='kubectl get persistentvolume --show-labels --watch -o=wide --namespace'
alias kgwowidesln='kubectl get --watch -o=wide --show-labels --namespace'
alias kgpowowidesln='kubectl get pods --watch -o=wide --show-labels --namespace'
alias kgdepwowidesln='kubectl get deployment --watch -o=wide --show-labels --namespace'
alias kgsecwowidesln='kubectl get secret --watch -o=wide --show-labels --namespace'
alias kgpvcwowidesln='kubectl get persistentvolumeclaim --watch -o=wide --show-labels --namespace'
alias kgpvwowidesln='kubectl get persistentvolume --watch -o=wide --show-labels --namespace'
alias kgwslowiden='kubectl get --watch --show-labels -o=wide --namespace'
alias kgpowslowiden='kubectl get pods --watch --show-labels -o=wide --namespace'
alias kgdepwslowiden='kubectl get deployment --watch --show-labels -o=wide --namespace'
alias kgsecwslowiden='kubectl get secret --watch --show-labels -o=wide --namespace'
alias kgpvcwslowiden='kubectl get persistentvolumeclaim --watch --show-labels -o=wide --namespace'
alias kgpvwslowiden='kubectl get persistentvolume --watch --show-labels -o=wide --namespace'
